### ISSUE TITLE
search occurrences for a time period (from start time to end time)

### ISSUE THREAD

**Issue by DeboraArlt** [bioatlas/SBDI4R#1]
current possibilities to filter for time when searching/downloading occurrences: using the fq argument to specify e.g. year: fq=c("year:2010 OR year:2019") will return occurrences for 2010 and 2019. But if I want to have all data for a time period, e.g. from 2010-2019 I would have to list all those years. Worse if I wanted data from say 1 May 2011 to 31 December 2017. With current package functionality I cannot easily search for a time period starting from-date (or from-year) and ending to-date (or to-year), or? I can only download data and then filter afterwards. would limiting search to a time period become more easily possible with facet search?

**Comment by aleruete** [comment]
I could add a function that helps creating text for the query and then processing the result so it matches your will. 

DA: ok, I think it would be really useful to be able to select occurrences for a time period (being able to specifiy e.g. year 1950-2010, and also 10 May 2003 - 23 October 2014)

**Comment by aleruete** [comment]
@DeboraArlt there is a possibility to use teh indexed field datum, but I find no way to retrieve any complete data to see the format. Otherwise, one can search by year and month (example added)

**Comment by DeboraArlt** [comment]
ok, searching using year and month is good enough for now.
