### ISSUE TITLE
fields for search

### ISSUE THREAD

**Issue by aleruete** [bioatlas/SBDI4R#10]
originally the argument "extra" requires that ..."Field names can be passed as full names (e.g. "Radiation - lowest period (Bio22)") rather than id ("el871"). " 
however, the e.g. environmental layer in bioatlas sbdi_fields(fields_type = "occurrence") does not have  other names or decription than elXXXX.

**Comment by shahmanash** [comment]
The uploaded layers are here:
https://spatial.bioatlas.se/ws/layers
Can you check if you are calling this API endpoint

**Comment by aleruete** [comment]
well, no. The function points to https://records.bioatlas.se/ws/index/fields (when wrapped using the base urls from bioatlas) and originally (the ALA4R package) points to https://biocache-ws.ala.org.au/ws/index/fields
 being the difference the downloadDescription e.g.:
in Bioatlas
"name": "cl10048",
"dataType": "string",
"indexed": true,
"stored": true,
"multivalue": false,
"docvalue": false,
"info": "https://spatial.bioatlas.se/ws/layers/view/more/cl10048",
"downloadName": "cl10048",
"classs": "Contextual"

to originally
"name": "cl1048",
"dataType": "string",
"indexed": true,
"stored": true,
"multivalue": false,
"docvalue": false,
"description": "IBRA 7 Regions",
"info": "https://sampling.ala.org.au/sampling-service/layers/view/more/cl1048",
"downloadName": "cl1048",
"downloadDescription": "IBRA 7 Regions",
"classs": "Contextual"

**Comment by aleruete** [comment]
for the "layers" lists `sbdi_fields(fields_type = "layers")` looks ok, though
