### ISSUE TITLE
Update URL in onload

### ISSUE THREAD

**Issue by shahmanash** [bioatlas/SBDI4R#15]
The url here https://github.com/biodiversitydata-se/SBDI4R/blob/master/R/onload.R#L33 should probably be 

https://spatial.bioatlas.se/alaspatial/ws

as in the original ALA4R
https://github.com/AtlasOfLivingAustralia/ALA4R/blob/master/R/onload.R#L28
or the NBN4R 
https://github.com/fozy81/NBN4R/blob/master/R/onload.R#L28

**Comment by aleruete** [comment]
OK, fixed... lets see if it breaks something ;)
