### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by shahmanash** [bioatlas/SBDI4R#16]
Add relevant permissible license if applicable

**Comment by aleruete** [comment]
Which one, we didn´t know from the begining which would be suitable

**Comment by shahmanash** [comment]
From the pages on R packages https://www.r-project.org/Licenses/ , the Dyntaxa R package https://github.com/bioatlas/dyntaxa and the Mirroreum  https://github.com/bioatlas/mirroreum, it seems GNU Affero General Public License v3.0 is the suitable one.
