### ISSUE TITLE
Search for redlisted species (NBN)

### ISSUE THREAD

**Issue by aleruete** [bioatlas/SBDI4R#33]
using an indexed species list [as the Swedish lists are not implemented in Bioatlas yet – can we provide an example with NBN data and list?

**Comment by aleruete** [comment]
@DeboraArlt I couldnt find an example of list you mention.

**Comment by DeboraArlt** [comment]
@aleruete I was thinking of a list like this: https://lists.nbnatlas.org/speciesListItem/list/dr2106. In the Spatial Portal https://spatial.nbnatlas.org/# one can search for records of species on the list: "add to map">species/use existing list

**Comment by aleruete** [comment]
the function is ready, just need the list as a resource.
